-- PayTrack: four-entity payroll master data schema for Supabase / PostgreSQL.
create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  base_salary numeric(14, 2) not null default 0 check (base_salary >= 0),
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  employee_code text not null unique,
  full_name text not null,
  position_id bigint not null references public.positions(id) on update cascade on delete restrict,
  email text,
  phone text,
  joined_at date not null default current_date,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now()
);

create table if not exists public.salary_components (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on update cascade on delete cascade,
  component_type text not null check (component_type in ('TUNJANGAN', 'POTONGAN')),
  name text not null,
  period date not null default date_trunc('month', current_date)::date,
  amount numeric(14, 2) not null default 0 check (amount >= 0),
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on update cascade on delete cascade,
  period date not null default date_trunc('month', current_date)::date,
  working_days integer not null check (working_days > 0),
  alpha_days integer not null default 0 check (alpha_days >= 0 and alpha_days <= working_days),
  created_at timestamptz not null default now(),
  unique (employee_id, period)
);

create index if not exists employees_position_id_idx on public.employees(position_id);
create index if not exists salary_components_employee_period_idx on public.salary_components(employee_id, period);
create index if not exists attendance_period_idx on public.attendance(period);

-- Preserve existing component data when upgrading from the previous schema.
do $$
begin
  if to_regclass('public.allowances') is not null then
    execute $migration$
      insert into public.salary_components (employee_id, component_type, name, period, amount, description)
      select employee_id, 'TUNJANGAN', name, period, amount, description from public.allowances
    $migration$;
  end if;
  if to_regclass('public.deductions') is not null then
    execute $migration$
      insert into public.salary_components (employee_id, component_type, name, period, amount, description)
      select employee_id, 'POTONGAN', name, period, amount, description from public.deductions
    $migration$;
  end if;
end $$;

drop table if exists public.allowances;
drop table if exists public.deductions;

alter table public.positions enable row level security;
alter table public.employees enable row level security;
alter table public.salary_components enable row level security;
alter table public.attendance enable row level security;

-- Demo-ready policy for a client-only app using the Supabase publishable key.
-- For production, replace these policies with authenticated-user/role-based access.
drop policy if exists "PayTrack public access" on public.positions;
drop policy if exists "PayTrack public access" on public.employees;
drop policy if exists "PayTrack public access" on public.salary_components;
drop policy if exists "PayTrack public access" on public.attendance;
create policy "PayTrack public access" on public.positions for all to anon, authenticated using (true) with check (true);
create policy "PayTrack public access" on public.employees for all to anon, authenticated using (true) with check (true);
create policy "PayTrack public access" on public.salary_components for all to anon, authenticated using (true) with check (true);
create policy "PayTrack public access" on public.attendance for all to anon, authenticated using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.positions, public.employees, public.salary_components, public.attendance to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

notify pgrst, 'reload schema';